name: SonarQube Analysis

#Se ejecuta cuando se hace un push a la rama feature
on:
  push:
    branches:
      - feature

jobs:
  sonar:
  #maquina virtual de github actions
    runs-on: ubuntu-latest

    steps:
    # clona el repositorio en la maquina virtual de github actions
      - uses: actions/checkout@v3

    # ejecuta el scanner de sonar
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://2ggt6n1j-9000.use2.devtunnels.ms